### ISSUE TITLE
Task list for 1.0.0

### ISSUE THREAD

**Issue by WhyAsh5114** [prisma-idb/idb-client-generator#52]
## Performance issues
Moving to individual classes for each model, this does take up quite some time to generate (~2s) even for small schemas, maybe this is due to using Node to write files, or I wrote terrible code (probably I wrote terrible code), but its something I'm willing to sacrifice for now till the complete API with relations and schema features can be implemented through IDB.

## For prisma-idb-generator 2.0.0
- [ ] Migrations

## Misc
- [x] Transactions

### [model field scalar types](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#model-field-scalar-types)

- [x] [String](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#string)
- [x] [Boolean](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#boolean)
- [x] [Int](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#int)
- [x] [BigInt](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#bigint)
- [x] [Float](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#float)
- [ ] [Decimal](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#decimal)
- [x] [DateTime](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#datetime)
- [ ] [Json](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#json)
- [x] [Bytes](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#bytes)
~~[Unsupported](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#unsupported)~~

### [model field type modifiers](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#model-field-type-modifiers)

- [ ] [[] modifier](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#-modifier)
- [ ] [? modifier](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#-modifier-1)

### [Attributes](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#attributes)

- [x] [@id](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#id)
- [ ] [@@id](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#id-1)
- [x] [@default](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#default)
- [x] [@unique](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#unique)
- [ ] [@@unique](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#unique-1)
- [ ] [@@index](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#index)
- [ ] [@relation](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#relation)
- [ ] [@map](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#map)
- [ ] [@@map](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#map-1)
- [ ] [@updatedAt](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#updatedat)
- [ ] [@ignore](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#ignore)
- [ ] [@@ignore](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#ignore-1)
- [ ] [@@schema](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#schema)

### [Attribute functions](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#attribute-functions)

- [x] [autoincrement()](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#autoincrement)
- [x] [cuid()](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#cuid)
- [x] [uuid()](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#uuid)
- [x] [now()](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#now)
~~[auto()](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#auto)~~
~~[sequence()](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#sequence)~~
~~[dbgenerated(...)](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#dbgenerated)~~

### Enums
- [x] [enum](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#enum)

### [Model queries](https://www.prisma.io/docs/orm/reference/prisma-client-reference#model-queries)
- [x] [findUnique()](https://www.prisma.io/docs/orm/reference/prisma-client-reference#findunique)
- [x] [findUniqueOrThrow()](https://www.prisma.io/docs/orm/reference/prisma-client-reference#finduniqueorthrow)
- [x] [findFirst()](https://www.prisma.io/docs/orm/reference/prisma-client-reference#findfirst)
- [x] [findFirstOrThrow()](https://www.prisma.io/docs/orm/reference/prisma-client-reference#findfirstorthrow)
- [x] [findMany()](https://www.prisma.io/docs/orm/reference/prisma-client-reference#findmany)
- [x] [create()](https://www.prisma.io/docs/orm/reference/prisma-client-reference#create)
- [x] [update()](https://www.prisma.io/docs/orm/reference/prisma-client-reference#update)
- [ ] [upsert()](https://www.prisma.io/docs/orm/reference/prisma-client-reference#upsert)
- [ ] [delete()](https://www.prisma.io/docs/orm/reference/prisma-client-reference#delete)
- [x] [createMany()](https://www.prisma.io/docs/orm/reference/prisma-client-reference#createmany)
- [x] [createManyAndReturn()](https://www.prisma.io/docs/orm/reference/prisma-client-reference#createmanyandreturn)
- [ ] [updateMany()](https://www.prisma.io/docs/orm/reference/prisma-client-reference#updatemany)
- [ ] [deleteMany()](https://www.prisma.io/docs/orm/reference/prisma-client-reference#deletemany)
- [x] [count()](https://www.prisma.io/docs/orm/reference/prisma-client-reference#count)
- [ ] [aggregate()](https://www.prisma.io/docs/orm/reference/prisma-client-reference#aggregate)
- [ ] [groupBy()](https://www.prisma.io/docs/orm/reference/prisma-client-reference#groupby)
~~[findRaw()](https://www.prisma.io/docs/orm/reference/prisma-client-reference#findraw)~~
~~[aggreagateRaw()](https://www.prisma.io/docs/orm/reference/prisma-client-reference#aggreagateraw)~~

### [Model query options](https://www.prisma.io/docs/orm/reference/prisma-client-reference#model-query-options)
- [x] [select](https://www.prisma.io/docs/orm/reference/prisma-client-reference#select)
- [x] [include](https://www.prisma.io/docs/orm/reference/prisma-client-reference#include)
- [ ] [omit (Preview)](https://www.prisma.io/docs/orm/reference/prisma-client-reference#omit-preview)
- [x] [where](https://www.prisma.io/docs/orm/reference/prisma-client-reference#where)
- [ ] [orderBy](https://www.prisma.io/docs/orm/reference/prisma-client-reference#orderby)
- [ ] [distinct](https://www.prisma.io/docs/orm/reference/prisma-client-reference#distinct)
~~[relationLoadStrategy (Preview)](https://www.prisma.io/docs/orm/reference/prisma-client-reference#relationloadstrategy-preview)~~

### [Nested queries](https://www.prisma.io/docs/orm/reference/prisma-client-reference#nested-queries)
- [x] [create](https://www.prisma.io/docs/orm/reference/prisma-client-reference#create-1)
- [x] [createMany](https://www.prisma.io/docs/orm/reference/prisma-client-reference#createmany-1)
- [ ] [set](https://www.prisma.io/docs/orm/reference/prisma-client-reference#set)
- [x] [connect](https://www.prisma.io/docs/orm/reference/prisma-client-reference#connect)
- [ ] [connectOrCreate](https://www.prisma.io/docs/orm/reference/prisma-client-reference#connectorcreate)
- [ ] [disconnect](https://www.prisma.io/docs/orm/reference/prisma-client-reference#disconnect)
- [ ] [update](https://www.prisma.io/docs/orm/reference/prisma-client-reference#update-1)
- [ ] [upsert](https://www.prisma.io/docs/orm/reference/prisma-client-reference#upsert-1)
- [ ] [delete](https://www.prisma.io/docs/orm/reference/prisma-client-reference#delete-1)
- [ ] [updateMany](https://www.prisma.io/docs/orm/reference/prisma-client-reference#updatemany-1)
- [ ] [deleteMany](https://www.prisma.io/docs/orm/reference/prisma-client-reference#deletemany-1)

### [Filter conditions and operators](https://www.prisma.io/docs/orm/reference/prisma-client-reference#filter-conditions-and-operators)
- [x] [equals](https://www.prisma.io/docs/orm/reference/prisma-client-reference#equals)
- [x] [not](https://www.prisma.io/docs/orm/reference/prisma-client-reference#not)
- [x] [in](https://www.prisma.io/docs/orm/reference/prisma-client-reference#in)
- [x] [notIn](https://www.prisma.io/docs/orm/reference/prisma-client-reference#notin)
- [x] [lt](https://www.prisma.io/docs/orm/reference/prisma-client-reference#lt)
- [x] [lte](https://www.prisma.io/docs/orm/reference/prisma-client-reference#lte)
- [x] [gt](https://www.prisma.io/docs/orm/reference/prisma-client-reference#gt)
- [x] [gte](https://www.prisma.io/docs/orm/reference/prisma-client-reference#gte)
- [x] [contains](https://www.prisma.io/docs/orm/reference/prisma-client-reference#contains)
- [x] [search](https://www.prisma.io/docs/orm/reference/prisma-client-reference#search)
- [x] [mode](https://www.prisma.io/docs/orm/reference/prisma-client-reference#mode)
- [x] [startsWith](https://www.prisma.io/docs/orm/reference/prisma-client-reference#startswith)
- [x] [endsWith](https://www.prisma.io/docs/orm/reference/prisma-client-reference#endswith)
- [ ] [AND](https://www.prisma.io/docs/orm/reference/prisma-client-reference#and)
- [ ] [OR](https://www.prisma.io/docs/orm/reference/prisma-client-reference#or)
- [ ] [NOT](https://www.prisma.io/docs/orm/reference/prisma-client-reference#not-1)

### [Relation filters](https://www.prisma.io/docs/orm/reference/prisma-client-reference#relation-filters)
- [ ] [some](https://www.prisma.io/docs/orm/reference/prisma-client-reference#some)
- [ ] [every](https://www.prisma.io/docs/orm/reference/prisma-client-reference#every)
- [ ] [none](https://www.prisma.io/docs/orm/reference/prisma-client-reference#none)
- [ ] [is](https://www.prisma.io/docs/orm/reference/prisma-client-reference#is)
- [ ] [isNot](https://www.prisma.io/docs/orm/reference/prisma-client-reference#isnot)

### [Scalar list methods](https://www.prisma.io/docs/orm/reference/prisma-client-reference#scalar-list-methods)
- [x] [set](https://www.prisma.io/docs/orm/reference/prisma-client-reference#set-1)
- [x] [push](https://www.prisma.io/docs/orm/reference/prisma-client-reference#push)
~~[unset](https://www.prisma.io/docs/orm/reference/prisma-client-reference#unset)~~

### [Scalar list filters](https://www.prisma.io/docs/orm/reference/prisma-client-reference#scalar-list-filters)
- [ ] [has](https://www.prisma.io/docs/orm/reference/prisma-client-reference#has)
- [ ] [hasEvery](https://www.prisma.io/docs/orm/reference/prisma-client-reference#hasevery)
- [ ] [hasSome](https://www.prisma.io/docs/orm/reference/prisma-client-reference#hassome)
- [ ] [isEmpty](https://www.prisma.io/docs/orm/reference/prisma-client-reference#isempty)
- [ ] [isSet](https://www.prisma.io/docs/orm/reference/prisma-client-reference#isset)
- [ ] [equals](https://www.prisma.io/docs/orm/reference/prisma-client-reference#equals-1)

### [Atomic number operations](https://www.prisma.io/docs/orm/reference/prisma-client-reference#atomic-number-operations)
- [ ] [Operators](https://www.prisma.io/docs/orm/reference/prisma-client-reference#operators)
